# AUTOGENERATED! DO NOT EDIT! File to edit: ../posts/2025-02-05-FastHTML-Pattern-List-Page-With-Form.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'index', 'add']

# %% ../nbs/2025-02-05-FastHTML-Pattern-List-Page-With-Form.ipynb 2
from fasthtml.common import *
from nbdev.export import nb_export

# %% ../nbs/2025-02-05-FastHTML-Pattern-List-Page-With-Form.ipynb 3
app, rt = fast_app()

@rt
def index():
    return (
        Grid(
            Div(
                H1("Your Items"),
                P("Here are your items:")
            ),
            id="grid"
        ),
        Div(
            H2("Add Item Form"),
            Form(
                Input(name="item", type="text", value="I'm an item"),
                Button("Submit"), 
                hx_post="/add", hx_target="#grid", hx_swap="beforeend"
            )
        )
    )

@rt
def add(item:str):
    return D(item)

serve()
